### ISSUE TITLE
Firefox版本的插件链接无法访问

### ISSUE THREAD

**Issue by zzhaolei** [taoso/webfeed#2]
README中的Firefox版本的插件链接无法访问 `https://addons.mozilla.org/zh-CN/firefox/addon/webfeed/`

**Comment by taoso** [comment]
之前我不小心删了帐号😂前两天想重新上传，结果 Firefox 要求使用 V3 版本，还得重新适配。确实有点伤。

**Comment by zzhaolei** [comment]
确实伤，现在Chrome也不接收新的V2版本的扩展了。

之前在Chrome上用这个插件，还挺好用的，想在Firefox上也用，没想到直接打不开了😂

**Comment by taoso** [comment]
我会尽快迁移到 MV3。因为 Chrome 很早就要求使用 MV3 接口了，改造成本应该不大。敬请期待。

**Comment by taoso** [comment]
等重新上线 Firefox 版再关这个问题哈

**Comment by zzhaolei** [comment]
期待新版本😁

**Comment by taoso** [comment]
@zzhaolei 两年过去了，中间发生了很多事。当时因为MV3改造延误了时间，最可悲的是 webfeed 这个 id 在此期间被别人注册了😂凡事要趁早呀～

另外，Firefox 的权限交互也发生很大的变化。WebFeed 因为要定时检查 RSS/Atom 更新以及确认当前页面是否有订阅链接，所以需要 all hosts 权限。但 Firefox 在默认情况下需要用户点击扩展图标才会授予单个域名的权限。用户需要到扩展配置的权限页面单独勾选才能授权全部域名。这种变化让 WebFeed 无法开箱即用，非常难受。

基于以上两种变化，再加上 Firefox 用户本来只有十多个，我已经放弃 Firefox 浏览器改改用回 Chrome 了。如果你还想体验，可以通过这个链接下载，但后续大概率是不维护了。

<https://addons.mozilla.org/firefox/downloads/file/4321955/a82ffcf7618d45059aed-0.9.0.xpi>
